NEST-499: Bug fixing for Azure blob storage requests
Lombiq/Orchard-Azure-Application-Insights pull request #78
Opened 2023-11-29 13:33 UTC by wAsnk

2023-11-29 14:05 UTC, Piedone requested changes

2023-11-29 14:05 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/Services/AzureBlobTelemetryFilter.cs
> +public class AzureBlobTelemetryFilter : ITelemetryProcessor
Comment why this is necessary.

2023-11-30 18:09 UTC, Piedone requested changes

2023-11-30 18:09 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// This will be used for RequestTelemetries.
Use `<see>` when referring to types, also in the 3 other cases below.

2023-11-30 18:09 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// <see cref="DependencyTelemetry.Data"/> or <see cref="RequestTelemetry.Url"/>. This is useful if you have a lot
This comment mistakenly references `DependencyTelemetry.Data`, and the one on `DependencyIgnoreFailureRegex` `RequestTelemetry.Url`.

2023-11-30 18:09 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// <example>You should use a regex pattern like "(?:\\/media\\/)".</example>
Why is the capture group necessary?

2023-11-30 18:09 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
>      /// <example>You should use a regex pattern like "(?:\\/favicon.ico$)|(?:\\/media\\/)".</example>
Media is not necessary anymore, no?

2023-11-30 18:09 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/Extensions/TelemetryExtensions.cs
> +    private static bool IsResult400(string code) =>
```suggestion
    private static bool IsResult4xx(string code) =>
```

2023-11-30 18:15 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// <example>You should use a regex pattern like "(?:\\/media\\/)".</example>
Because you asked for it :D

2023-11-30 18:15 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// <example>You should use a regex pattern like "(?:\\/media\\/)".</example>
To be fair it is not necessary, the developer can decide if it is needed.

2023-11-30 18:16 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
>      /// <example>You should use a regex pattern like "(?:\\/favicon.ico$)|(?:\\/media\\/)".</example>
It is just an example, if someone wants do to that why not?

2023-11-30 18:26 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
>      /// <example>You should use a regex pattern like "(?:\\/favicon.ico$)|(?:\\/media\\/)".</example>
Whatever, changed it.

2023-11-30 20:08 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// <example>You should use a regex pattern like "(?:\\/media\\/)".</example>
But I didn't :). The group was necessary when using more patterns with `|`, but it's not necessary for matching a single one. I asked for the group to be a non-capturing one for performance then, but if groups are not needed then of course having a non-capturing one doesn't make sense either.

2023-11-30 20:09 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
>      /// <example>You should use a regex pattern like "(?:\\/favicon.ico$)|(?:\\/media\\/)".</example>
The examples should naturally be sensible. If you would not ignore media here (but only for dependencies) then we shouldn't have it here either.

2023-11-30 20:20 UTC, Piedone requested changes

2023-11-30 20:20 UTC, Piedone commented on Lombiq.Hosting.Azure.ApplicationInsights/Extensions/TelemetryExtensions.cs
> +#pragma warning disable S100 // Making an exception here because 4xx describes it better.
Keep the auto-generated comment about the rule, so we know what's actually suppressed, see https://github.com/Lombiq/.NET-Analyzers/blob/dev/Lombiq.Analyzers/Docs/UsingAnalyzersDuringDevelopment.md#practices-on-suppressing-a-rule-for-a-given-piece-of-code:~:text=Example%20where%20the%20%23pragma%20suppress%20is%20suitable.

2023-11-30 20:22 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
>      /// <example>You should use a regex pattern like "(?:\\/favicon.ico$)|(?:\\/media\\/)".</example>
Yeah as I said, changed it.

2023-11-30 20:23 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/Extensions/TelemetryExtensions.cs
> +#pragma warning disable S100 // Making an exception here because 4xx describes it better.
There was no auto-generated comment.

2023-11-30 20:24 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/Extensions/TelemetryExtensions.cs
> +#pragma warning disable S100 // Making an exception here because 4xx describes it better.
So what in that case?

2023-11-30 20:25 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/Extensions/TelemetryExtensions.cs
> +#pragma warning disable S100 // Making an exception here because 4xx describes it better.
Nvm, googled it.

2023-11-30 20:53 UTC, wAsnk commented on Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs
> +    /// <example>You should use a regex pattern like "(?:\\/media\\/)".</example>
OK

2023-11-30 22:05 UTC, merged